# Generated by Django 5.1.1 on 2024-10-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
